# .github/workflows/renew-graph-subscription.yml
name: Renew Graph Subscription

on:
  # manual trigger
  workflow_dispatch:
  # scheduled trigger every 12 hours
  schedule:
    - cron: '0 */12 * * *'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Renew MSFT Graph Subscription
        run: |
          curl --request POST \
               --url https://briefly-theta.vercel.app/api/graph/subscribe \
               --header "Content-Type: application/json"
