name: Renew Graph Subscription

# Run every 45 minutes
on:
  schedule:
    - cron: '*/45 * * * *'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Renew subscription
        run: |
          curl -X POST https://briefly-theta.vercel.app/api/graph/subscribe \
               -H "Content-Type: application/json"
